url: "https://pachulski.dev" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Nick Pachulski" # the name of your site, e.g. ACME Corp.
